name: makepkg

on:
  push:
    branches:
      - gruvbox
    tags:
      - '*'
  workflow_dispatch:

jobs:
  makepkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pkgbuild branch
        uses: actions/checkout@v2
        with:
          ref: pkgbuild

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:base-devel
          options: -v ${{ github.workspace }}:/home/builder
          shell: bash
          run: |
            cd /home/builder
            pacman -Syy \
              && pacman -S --noconfirm \
                git \
                freetype2 \
                libx11 \
                libxcb \
                libxft \
                libxinerama
            chmod o+rw . -R \
              && runuser -u nobody -- makepkg -scCfm --noconfirm

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.pkg.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
